### PR TITLE
Log command torques from IOB

### PR DESCRIPTION
**Pull request by rohanpsingh**
This creates a new `InPort` named `cmdTauInIn` which is expected to receive the commanded torques at the IOB level
(independent of position/velocity/torque control_mode)
It should be connected to the `ctau` port of `RobotHardware` as follows:
```
connectPorts(rh.port("ctau"), mc.port("cmdTauIn"))
```

For now, the received data is directly logged through `controller().logger()`.

### CODE REVIEW

**Comment by rohanpsingh** [comment]
I confirmed that I can log the command torques on the real robot!

**Comment by rohanpsingh** [comment]
In order to use this feature, we need to add the following lines to our project's `exp_mc.py`:
`connectPorts(rh.port("ctau"), mc.port("cmdTauIn"))`
But since I don't have access to hrp-choreonoid, I cannot make that commit.

**Comment by gergondet** [comment]
Thanks @rohanpsingh, I will close #23 since this contains the same commits

**Comment by gergondet** [comment]
> But since I don't have access to hrp-choreonoid, I cannot make that commit.

I think this has been fixed in recent days. Can you send a MR there?

**Comment by rohanpsingh** [comment]
Thank you @gergondet,
Here is the MR you requested: https://gite.lirmm.fr/choreonoid-hrp-installation/hrp-choreonoid/-/merge_requests/36

**Pull request merged**
